# Generated by Django 5.2.8 on 2025-12-05 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('voter', 'Voter'), ('candidate', 'Candidate'), ('auditor', 'Auditor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('party', models.CharField(blank=True, max_length=100, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VoterProfile',
            fields=[
                ('voter_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('course', models.CharField(max_length=50)),
                ('year_level', models.IntegerField()),
                ('is_eligible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=250)),
                ('ip_address', models.CharField(max_length=50)),
                ('prev_hash', models.CharField(max_length=64)),
                ('curr_hash', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=50)),
                ('latency_ms', models.IntegerField()),
                ('packet_loss', models.FloatField()),
                ('event_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('max_winners', models.IntegerField(default=1)),
                ('choice_type', models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], max_length=10)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.election')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=50)),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encrypted_vote', models.TextField()),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('submission_latency_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
                ('voter_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('candidate_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VoteReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ack_hash', models.CharField(max_length=64)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('client_timestamp', models.DateTimeField()),
                ('retransmissions', models.IntegerField(default=0)),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.vote')),
            ],
        ),
        migrations.CreateModel(
            name='TallyResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_count', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
                ('candidate_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('candidate_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateForPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
                ('candidate_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidateprofile')),
            ],
        ),
    ]
