# Generated by Django 6.0.4 on 2026-04-30 07:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['position', 'voter__user__last_name']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='alias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='api.election'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(blank=True, choices=[('Chairperson', 'Chairperson'), ('Vice Chairperson', 'Vice Chairperson'), ('Councilor', 'Councilor')], max_length=32),
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
