# Generated by Django 5.2.7 on 2025-12-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='idempotency_key',
            field=models.CharField(max_length=64),
        ),
    ]
