# Generated by Django 5.2.7 on 2025-12-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_voterprofile_voter_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
