# Generated by Django 6.0.4 on 2026-05-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ballot_ballotline'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Shown on the ballot; optional.', null=True, upload_to='candidate_photos/'),
        ),
    ]
