# Generated by Django 6.0.4 on 2026-05-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_candidate_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='degree_program',
            field=models.CharField(blank=True, help_text='Degree program name for turnout / auditor charts.', max_length=128),
        ),
        migrations.AddField(
            model_name='voter',
            name='year_level',
            field=models.CharField(blank=True, help_text='Academic year level (e.g. 1–5); optional demographic.', max_length=32),
        ),
    ]
