# Generated by Django 6.0.4 on 2026-05-02 11:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_election_enrollments(apps, schema_editor):
    """Match pre-roster auditor eligibility: ballot ∪ candidates ∪ general electorate."""
    from django.db.models import Exists, OuterRef

    ElectionEnrollment = apps.get_model("api", "ElectionEnrollment")
    Election = apps.get_model("api", "Election")
    Voter = apps.get_model("api", "Voter")
    Ballot = apps.get_model("api", "Ballot")
    Candidate = apps.get_model("api", "Candidate")

    rows = []
    for election in Election.objects.all():
        ballot_here = Ballot.objects.filter(
            election_id=election.pk, voter_id=OuterRef("pk")
        )
        cand_here = Candidate.objects.filter(
            election_id=election.pk, voter_id=OuterRef("pk")
        )
        cand_elsewhere = Candidate.objects.filter(voter_id=OuterRef("pk")).exclude(
            election_id=election.pk
        )
        for vid in (
            Voter.objects.filter(
                Exists(ballot_here) | Exists(cand_here) | (~Exists(cand_elsewhere))
            )
            .values_list("pk", flat=True)
            .iterator()
        ):
            rows.append(
                ElectionEnrollment(election_id=election.pk, voter_id=vid)
            )

    if not rows:
        return
    ElectionEnrollment.objects.bulk_create(rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_voter_year_level_degree_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_enrollments', to='api.voter')),
            ],
            options={
                'indexes': [models.Index(fields=['election', 'voter'], name='api_electio_electio_44961b_idx')],
                'constraints': [models.UniqueConstraint(fields=('election', 'voter'), name='api_election_enrollment_unique_election_voter')],
            },
        ),
        migrations.RunPython(backfill_election_enrollments, noop_reverse),
    ]
