# Generated by Django 6.0.4 on 2026-05-02 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ballot_submission_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotline',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ballot_lines', to='api.candidate'),
        ),
        migrations.AlterField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
