# Generated by Django 6.0.4 on 2026-05-02 20:42

import django.db.models.deletion
from django.db import migrations, models


def _sqlite_rebuild_candidate_ballotline(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != "sqlite":
        raise RuntimeError(
            "Migration 0014_candidate_per_election only includes an automated "
            "database rebuild for SQLite. Use SQLite for local dev, or add a "
            "PostgreSQL/MySQL rebuild path before deploying."
        )
    with connection.cursor() as cursor:
        cursor.execute("PRAGMA foreign_keys = OFF")
        cursor.execute(
            '''
            CREATE TABLE "api_candidate_new" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "voter_id" bigint NOT NULL REFERENCES "api_voter" ("user_id") DEFERRABLE INITIALLY DEFERRED,
                "alias" varchar(100) NOT NULL,
                "created_at" datetime NOT NULL,
                "description" text NOT NULL,
                "election_id" bigint NULL REFERENCES "api_election" ("id") DEFERRABLE INITIALLY DEFERRED,
                "party" varchar(100) NOT NULL,
                "position" varchar(32) NOT NULL,
                "updated_at" datetime NOT NULL,
                "profile_photo" varchar(100) NULL
            )
            '''
        )
        cursor.execute(
            '''
            INSERT INTO "api_candidate_new" (
                "voter_id", "alias", "created_at", "description", "election_id",
                "party", "position", "updated_at", "profile_photo"
            )
            SELECT
                "voter_id", "alias", "created_at", "description", "election_id",
                "party", "position", "updated_at", "profile_photo"
            FROM "api_candidate"
            '''
        )
        cursor.execute(
            '''
            CREATE TABLE "api_ballotline_new" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "position" varchar(32) NOT NULL,
                "abstain" bool NOT NULL,
                "ballot_id" bigint NOT NULL REFERENCES "api_ballot" ("id") DEFERRABLE INITIALLY DEFERRED,
                "candidate_id" bigint NULL REFERENCES "api_candidate_new" ("id") DEFERRABLE INITIALLY DEFERRED
            )
            '''
        )
        cursor.execute(
            '''
            INSERT INTO "api_ballotline_new" ("id", "position", "abstain", "ballot_id", "candidate_id")
            SELECT
                bl."id",
                bl."position",
                bl."abstain",
                bl."ballot_id",
                CASE
                    WHEN bl."candidate_id" IS NULL THEN NULL
                    ELSE (SELECT cn."id" FROM "api_candidate_new" cn WHERE cn."voter_id" = bl."candidate_id")
                END
            FROM "api_ballotline" AS bl
            '''
        )
        cursor.execute('DROP TABLE "api_ballotline"')
        cursor.execute('ALTER TABLE "api_ballotline_new" RENAME TO "api_ballotline"')
        cursor.execute('DROP TABLE "api_candidate"')
        cursor.execute('ALTER TABLE "api_candidate_new" RENAME TO "api_candidate"')
        cursor.execute(
            'CREATE UNIQUE INDEX "api_candidate_unique_election_voter" '
            'ON "api_candidate" ("election_id", "voter_id")'
        )
        cursor.execute("PRAGMA foreign_keys = ON")


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("api", "0013_electionenrollment_public_voter_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _sqlite_rebuild_candidate_ballotline,
                    _noop_reverse,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="candidate",
                    name="id",
                    field=models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                migrations.AlterField(
                    model_name="candidate",
                    name="voter",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_entries",
                        to="api.voter",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="candidate",
                    constraint=models.UniqueConstraint(
                        fields=("election", "voter"),
                        name="api_candidate_unique_election_voter",
                    ),
                ),
            ],
        ),
    ]
